"""users table

Revision ID: 154ad97320db
Revises: 9923f45ff8c4
Create Date: 2025-03-18 14:43:31.193922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154ad97320db'
down_revision: Union[str, None] = '9923f45ff8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('users', 'phone_verification_code')
    op.drop_column('users', 'email_verification_code')
    # ### end Alembic commands ###
