"""add files topic table

Revision ID: 3b278c4a9f23
Revises: 2927a9ca6e9f
Create Date: 2025-03-27 15:54:21.100566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b278c4a9f23'
down_revision: Union[str, None] = '2927a9ca6e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_files_id'), 'topic_files', ['id'], unique=False)
    op.create_index(op.f('ix_topic_files_topic_id'), 'topic_files', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_files_topic_id'), table_name='topic_files')
    op.drop_index(op.f('ix_topic_files_id'), table_name='topic_files')
    op.drop_table('topic_files')
    # ### end Alembic commands ###
