"""users table

Revision ID: 4b674f876d0e
Revises: cabe6ad6591e
Create Date: 2025-03-20 19:13:16.041630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b674f876d0e'
down_revision: Union[str, None] = 'cabe6ad6591e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
