"""users table

Revision ID: 4b842d4e167b
Revises: bfa3795d1ba4
Create Date: 2025-03-18 21:25:54.409981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b842d4e167b'
down_revision: Union[str, None] = 'bfa3795d1ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    
    # Если email не подходит, можно создать уникальное значение на основе id:
    op.execute("UPDATE users SET name = 'user_' || id WHERE name IS NULL")
    
    # 3. Изменяем столбец, устанавливая ограничение NOT NULL
    op.alter_column('users', 'name', nullable=False)
    
    # 4. Создаём уникальный индекс
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
