"""users table

Revision ID: 98230460b3f6
Revises: 880ab5b9871b
Create Date: 2025-03-22 16:14:08.693146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98230460b3f6'
down_revision: Union[str, None] = '880ab5b9871b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cover_photo', sa.String(), nullable=True))
    op.drop_column('users', 'cover_photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cover_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'cover_photo')
    # ### end Alembic commands ###
