"""topic table fix

Revision ID: b3409960f383
Revises: d3d05c833b26
Create Date: 2025-03-30 13:41:15.083739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3409960f383'
down_revision: Union[str, None] = 'd3d05c833b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('dislike_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_replies_id'), 'forum_replies', ['id'], unique=False)
    op.create_table('forum_reply_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['forum_replies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_reply_files_id'), 'forum_reply_files', ['id'], unique=False)
    op.create_table('reply_likes',
    sa.Column('reply_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_like', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['forum_replies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_index('ix_replies_id', table_name='replies')
    op.drop_table('replies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name='replies_topic_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='replies_pkey')
    )
    op.create_index('ix_replies_id', 'replies', ['id'], unique=False)
    op.drop_table('reply_likes')
    op.drop_index(op.f('ix_forum_reply_files_id'), table_name='forum_reply_files')
    op.drop_table('forum_reply_files')
    op.drop_index(op.f('ix_forum_replies_id'), table_name='forum_replies')
    op.drop_table('forum_replies')
    # ### end Alembic commands ###
