"""fix group buy table

Revision ID: c7cc297e2d2f
Revises: e6681763c461
Create Date: 2025-04-04 09:35:21.019681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7cc297e2d2f'
down_revision: Union[str, None] = 'e6681763c461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_buys', sa.Column('delivery_time', sa.Integer(), nullable=True))
    op.add_column('group_buys', sa.Column('delivery_location', sa.String(length=255), nullable=True))
    op.add_column('group_buys', sa.Column('transportation_cost', sa.Text(), nullable=True))
    op.add_column('group_buys', sa.Column('participation_terms', sa.Text(), nullable=True))
    op.add_column('group_buys', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_buys', 'image_url')
    op.drop_column('group_buys', 'participation_terms')
    op.drop_column('group_buys', 'transportation_cost')
    op.drop_column('group_buys', 'delivery_location')
    op.drop_column('group_buys', 'delivery_time')
    # ### end Alembic commands ###
